### ISSUE TITLE
Problem with make -j

### ISSUE THREAD

**Issue by aaronweiss8** [Derecho-Project/cascade#10]
I am having a problem installing Cascade because it gives me the following error when I run make -j:
In file included from /home/ajw242/workspace/cascade/include/cascade/service_server_api.hpp:2:0,
                 from /home/ajw242/workspace/cascade/src/service/ondata_library_example.cpp:1:
/home/ajw242/workspace/cascade/include/cascade/service.hpp:7:10: fatal error: derecho/utils/time.h: No such file or directory
 #include <derecho/utils/time.h>
For reference, I installed cloned cascade and derecho into a workspace directory. I had no problem installing derecho (I think) and was able to add it the install path opt-dev. In there I checked that opt-dev had the proper lib, include, and share folders and I believe they were okay. Does anyone know why I would get this error when running make -j?

**Comment by mpmilano** [comment]
Hi Aaron, 

The Cascade configuration assumes Derecho is installed on a system-registered include path.  Can you compile this small test:

```
#include <derecho/core/derecho.hpp>

int main(){}
```

**Comment by songweijia** [comment]
Hi Aaron,

I think you should add the derecho include path and library path to let
cascade know where derecho is if it is not installed in the standard system
path.

try the following before building/running cascade:

export C_INCLUDE_PATH=<derecho_install_path>/include
export CPLUS_INCLUDE_PATH=<derecho_install_path>/include
export LIBRARY_PATH=<derecho_install_path>lib
export LD_LIBRARY_PATH=<derecho_install_path>/lib
export CMAKE_PREFIX_PATH=<derecho_install_path>/

Best Regards,
Weijia Song
Department of Computer Science
Cornell University

**Comment by aaronweiss8** [comment]
Hello Weijia,

So I actually already had a bash script  that set those variables, but it did not work. Is there some other step prior to setting up the environment that I should also check?

**Comment by songweijia** [comment]
I saw "env.sh" in your folder. There are some STRANGE and INVISIBLE
characters at the end of each line, which are appended to the variables,
making WRONG paths. Delete them and try again.

**Comment by songweijia** [comment]
@aaronweiss8 Aaron, did that solve your issue? Please let me know.

**Comment by aaronweiss8** [comment]
Yes I was I had to run make DESDIR="" install to install cascade versus make install.
