### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Panlichen** [Derecho-Project/cascade#15]
https://github.com/Derecho-Project/cascade/blob/1ee2f534bb6f32576c8a90245f339643f403aeeb/src/service/fuse_client.cpp#L165
During `make`, it throws an error saying `sorry, unimplemented: non-trivial designated initializers not supported` 5 times, all pointing to this line. The method mentioned in [Stackoverflow](https://stackoverflow.com/questions/31215971/non-trivial-designated-initializers-not-supported) does not work.

Then I modify it to 
```c++
...
static struct fuse_lowlevel_ops fs_ops;
...
int main(int argc, char** argv) {
    fs_ops.init       = fs_init;
    fs_ops.destroy    = fs_destroy;
    fs_ops.lookup     = fs_lookup;
    fs_ops.getattr    = fs_getattr;
    fs_ops.open       = fs_open;
    fs_ops.read       = fs_read;
    fs_ops.release    = fs_release;
    fs_ops.readdir    = fs_readdir;
...
```
`make` succeeded.

I installed fuse v3.10.0.

**Comment by mpmilano** [comment]
What compiler (and what version) are you using?

**Comment by Panlichen** [comment]
g++ (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0

**Comment by mpmilano** [comment]
The Designated initializer syntax you're seeing here is supported in gcc-8 and later.

**Comment by Panlichen** [comment]
Thank you, got it, I'll try.

**Comment by Panlichen** [comment]
Merry Christmas~

**Comment by songweijia** [comment]
@mpmilano Thank you, Matthew!
