### ISSUE TITLE
Calculation of span

### ISSUE THREAD

**Issue by Panlichen** [Derecho-Project/cascade#18]
https://github.com/Derecho-Project/cascade/blob/b5d0402193c326045cb9e9e35d8fb3210cd5bba7/src/service/data_path_logic/cnn_classifier_perf.cpp#L229
Maybe`span_ns` should be calculated as `max_recv_ts - before_send_message_ts[0]`, not `max_recv_ts - send_message_ts[0]`?

**Comment by songweijia** [comment]
The send_message_ts[0] and before_send_message_ts[0] are almost equal: the difference is the time enqueuing the first message. But, sure, we should include that.
