### ISSUE TITLE
Calculation of latency std_dev

### ISSUE THREAD

**Issue by Panlichen** [Derecho-Project/cascade#19]
https://github.com/Derecho-Project/cascade/blob/b5d0402193c326045cb9e9e35d8fb3210cd5bba7/src/service/data_path_logic/cnn_classifier_perf.cpp#L240
Should print `std_dev/1e12` as millisecond due to the previous square operation.

**Comment by songweijia** [comment]
Please read this:https://en.wikipedia.org/wiki/Standard_deviation
