### ISSUE TITLE
Unable to run the client using pythonAPI

### ISSUE THREAD

**Issue by FarrukhRZ** [Derecho-Project/cascade#31]
Everytime I try to run a python client using the cascade_py, it gives this port error
python3 interactive_test.py. The cascade_client command works fine though
> ERROR on binding to socket in ConnectionListener: Address already in use
> Port is: 32645
> Traceback (most recent call last):
>  File "interactive_test.py", line 244, in <module>
>    main2()
>  File "interactive_test.py", line 17, in main2
>    a = cascade_py.ServiceClientAPI()
>RuntimeError: connection_listener: bind() failed

**Comment by sagarjha** [comment]
That's a linux error. You have another application running that is using the same port. It might even be another Cascade server that was started in the past.

Check out this stackoverflow link: https://stackoverflow.com/questions/15198834/bind-failed-address-already-in-use. The second and the third answers (sorted by votes) are useful.

**Comment by FarrukhRZ** [comment]
> That's a linux error. You have another application running that is using the same port. It might even be another Cascade server that was started in the past.
> 
Ummm, but how can I change the port of my client? I cannot see any options in the py file

**Comment by sagarjha** [comment]
My suggestion is to find the program that is using the port 32645 and kill it.

**Comment by FarrukhRZ** [comment]
One of the cascade_server nodes is using that port and I don't think that it is very wise to kill it :/

**Comment by sagarjha** [comment]
Okay, I see. @songweijia knows more about the configuration of Cascade. He can help you with the problem.

**Comment by FarrukhRZ** [comment]
Ahan, thanks for the help.

**Comment by songweijia** [comment]
@FarrukhRZ, first of all, thank you for trying it out. Could you let me know your setup and how you start those server/client processes? Generally, each node needs its own configuration file. The ports in those files should not conflict. I guess your client node is either loading the same configuration file being used by a server node, or the ports in the configuration file conflict.

**Comment by FarrukhRZ** [comment]
@songweijia I first run 6 server nodes, one in each of the 6 files (n0 to n5). Then I just run the python test file in the python directory under the cascade service directory.

**Comment by FarrukhRZ** [comment]
Wow, I ran it in the n6 directory and it worked!! thank you sm @songweijia

**Comment by songweijia** [comment]
Yes, this is how we design an external client. No, you cannot run more than one external client using the same configuration. Although you can have more configuration files to support multiple clients, we don't recommend that. An external client is considered a relatively stable node -- it has access to a thick RDMA channel to communicate with cascade servers. If you are thinking of many ephemeral clients that come and go frequently on a same node, using many external clients is not efficient. In such a case, you should aggregate the request from ephemeral clients and use only one external client.
