### ISSUE TITLE
A restarting Cascade client may freeze [investigated and solution proposed]

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/cascade#54]
Sometimes, we write a bash script calling a cascade client a couple of times, for example,  to set up the application pools. The `cascade_client` command following another could freeze nondeterministically.

Thiago @tgarr identifies that the issue is caused by [two lines](https://github.com/Derecho-Project/derecho/blob/fd51e6950c0eac889f819af2f2c0059c94a8b2cd/src/core/connection_manager.cpp#L113-L114) in derecho code, which skipped creating a new connection for the coming-back external cascade client (`cascade_client`). He enforced recreation of the connection by commenting on the above two lines, and the phenomenon disappears.

[Explanation] In the current Derecho implementation, the external client leaves brutally without notifying the Derecho group member. In the above case, the Derecho group member is the `cascade_server` process. The group member will eventually find out when the P2P heartbeats fail and clean it up (with some annoying error messages we have wanted to remove). However, the external client comes can goes frequently because the bash calls a couple of consecutive `cascade_client` commands. Sometimes, before the `cascade_server` process detects the leaving of a previous external client, a new external client with the same node ID tries to connect, triggering the condition in the above [two lines](https://github.com/Derecho-Project/derecho/blob/fd51e6950c0eac889f819af2f2c0059c94a8b2cd/src/core/connection_manager.cpp#L113-L114).

[Solution Proposal] I propose to introduce a graceful quitting procedure for a leaving external client. It not only solves the above issue but also gets rid of the annoying error messages. We should only report errors when ABNORMAL things happen.

**Comment by tgarr** [comment]
Commenting out those two lines actually doesn't solve the issue completely. The client doesn't freeze any more and the server doesn't enter an inconsistent state, however the client gets libfabric error -16 (-FI_EBUSY) most of the time (at least using TCP, I haven't tried with RDMA), which means "Device or resource busy". 

I agree that a "graceful exit" is the best solution. But can we do something about this -16 error in the client? Wait and try again maybe? It's a small thing but it can break simple setup scripts that use the command line client, which is not very nice for a 1.0 product release.

**Comment by tgarr** [comment]
New update: I tested on Fractus with TCP and RDMA. I had the same issue with TCP (as in my local machine), however it works fine with RDMA. So the problem seems to be limited to TCP. The code path is the same, so maybe it's something in libfabric?

**Comment by songweijia** [comment]
I guess that libfabric has an issue connecting to the same remote ip/port without cleaning everything up. I prefer the graceful exit approach instead of fixing something caused by a problematic workaround. What do you think, @tgarr ?

**Comment by tgarr** [comment]
Agreed!
